### ISSUE TITLE
System.EntryPointNotFoundException of LLVM.InitializeNativeAsmPrinter()

### ISSUE THREAD

**Issue by CWKSC** [dotnet/LLVMSharp#200]
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="libLLVM" Version="15.0.0" />
    <PackageReference Include="LLVMSharp" Version="5.0.0" />
  </ItemGroup>

</Project>
```

![image](https://user-images.githubusercontent.com/53114952/193643506-c155ffaf-3fb1-4c14-95b4-e6a82b87540f.png)

```csharp
LLVM.InitializeNativeAsmPrinter();
LLVM.InitializeNativeTarget();
```

```
System.EntryPointNotFoundException: 'Unable to find an entry point named 'LLVMInitializeNativeAsmPrinter' in DLL 'libLLVM'.'
```

**Comment by tannergooding** [comment]
Hmmm, this does appear to be missing from the exports in the official `LLVM-C.dll` binary.

**Comment by tannergooding** [comment]
@CWKSC, just noticed but you're referencing `LLVMSharp 5.0.0`. Can you please update to v15.0.0

**Comment by CWKSC** [comment]
Do you mean changing `LLVMSharp` from `5.0.0` to `15.0.0`

```diff
<ItemGroup>
    <PackageReference Include="libLLVM" Version="15.0.0" />
-   <PackageReference Include="LLVMSharp" Version="5.0.0" />
+   <PackageReference Include="LLVMSharp" Version="15.0.0" />
</ItemGroup>
```

But the latest version of `LLVMSharp` is `5.0.0` in NuGet.

![image](https://user-images.githubusercontent.com/53114952/200493927-424f760a-590e-4582-a07d-3246f11ecc0a.png)

This will produce [NU1102 Unable to find package](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1102?f1url=%3FappId%3DDev16IDEF1%26l%3DZH-TW%26k%3Dk(NU1102)%26rd%3Dtrue) if I directly change it.

If I understand correctly, the library works when both `libLLVM` and `LLVMSharp` are installed.

If I only install `LLVMSharp`

![image](https://user-images.githubusercontent.com/53114952/200495108-02f150b8-b193-4b80-8f0e-b57a9c82d5b2.png)

This will be using outdated `LibLLVM (5.0.1)`

When I install both,

![image](https://user-images.githubusercontent.com/53114952/200495376-67e8d5f5-afad-4730-bf5a-c0eae6eea2d5.png)

The dependency inside LLVMSharp is changed.

Sorry if any misunderstanding.

**Comment by tannergooding** [comment]
The latest version  is 15.0.0-beta1: https://www.nuget.org/packages/LLVMSharp/15.0.0-beta1

It's not visible because you don't have the include pre-release check box checked.

The 5.0.0 version is over 5 years old and significantly out of date and while the new version is still marked "pre-release" it is generally better and overall more stable.

**Comment by tannergooding** [comment]
Yes. The entire API surface was redone to be more correct, have fewer breaking changes, and to be blittable.
