### ISSUE TITLE
std::bad_alloc + seg fault when creating function

### ISSUE THREAD

**Issue by AnErrupTion** [dotnet/LLVMSharp#202]
Hello!

I'm encountering a very weird error when using those bindings. If I create an empty module then dump it, it works fine:
```cs
using LLVMSharp.Interop;

var module = LLVMModuleRef.CreateWithName("Test");
module.Dump();
```

But as soon as I add a function like this, before dumping:
```cs
module.AddFunction("main", LLVMTypeRef.Void);
```

It crashes and seg faults like this:
```
; ModuleID = 'Test'
source_filename = "Test"
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Process finished with exit code 134.
```

I've never encountered this, and in fact, it only seems to happen with those bindings, as the ``llvm-sys`` Rust bindings work just fine. I've tried LLVMSharp 14 and 15 (having 14 on my system), but same issue.

I'm using Fedora 36 with LLVM 14.0.5, if that helps.

**Comment by tannergooding** [comment]
I'll try to take a look this weekend. Might end up having to debug into libLLVM to see what's failing on the native side.

**Comment by AnErrupTion** [comment]
@tannergooding Any news?

**Comment by AnErrupTion** [comment]
This issue still seems to occur, even on the JavaCPP bindings. However, I tried the C++ API and it works just fine. I'm not sure what could be the cause of this error...

**Comment by AnErrupTion** [comment]
Actually, it was my fault all along. I was using directly the void type instead of creating a function type...
