### ISSUE TITLE
Consistent AccessViolationException when calling BuildCall2

### ISSUE THREAD

**Issue by DuncanMcPherson** [dotnet/LLVMSharp#227]
I have a project that is using LLVM and I am trying to write my own implementation of the C Standard library's strlen. I got what I though would be a valid declaration:
```C#
private void DeclareStrLen()
{
    var strlenType = LLVMTypeRef.CreateFunction(LLVMTypeRef.Int32,
        new[] { LLVMTypeRef.CreatePointer(LLVMTypeRef.Int8, 0) }, false);
    var strlenFunction = _module.GetNamedFunction("strlen");
    if (strlenFunction.Handle != IntPtr.Zero)
    {
        return;
    }

    strlenFunction = _module.AddFunction("strlen", strlenType);

    var entry = strlenFunction.AppendBasicBlock("entry");
    _builder.PositionAtEnd(entry);

    var str = strlenFunction.GetParam(0);

    var length = _builder.BuildAlloca(LLVMTypeRef.Int32, "length");
    _builder.BuildStore(LLVMValueRef.CreateConstInt(LLVMTypeRef.Int32, 0, false), length);

    var loopCond = strlenFunction.AppendBasicBlock("loopCond");
    var loopBody = strlenFunction.AppendBasicBlock("loopBody");
    var loopEnd = strlenFunction.AppendBasicBlock("loopEnd");

    _builder.BuildBr(loopCond);

    _builder.PositionAtEnd(loopCond);
    var currentIndex = _builder.BuildLoad2(LLVMTypeRef.Int32, length, "currentIndex");
    var currentCharPtr = _builder.BuildInBoundsGEP2(LLVMTypeRef.Int8, str, new LLVMValueRef[] { currentIndex });
    var currentChar = _builder.BuildLoad2(LLVMTypeRef.Int8, currentCharPtr, "currentChar");
    var isNullChar = _builder.BuildICmp(LLVMIntPredicate.LLVMIntEQ, currentChar,
        LLVMValueRef.CreateConstInt(LLVMTypeRef.Int8, 0, false), "isNullChar");

    _builder.BuildCondBr(isNullChar, loopEnd, loopBody);

    _builder.PositionAtEnd(loopBody);
    var newIndex = _builder.BuildAdd(currentIndex, LLVMValueRef.CreateConstInt(LLVMTypeRef.Int32, 1, false),
        "newIndex");
    _builder.BuildStore(newIndex, length);
    _builder.BuildBr(loopCond);

    _builder.PositionAtEnd(loopEnd);
    var finalLength = _builder.BuildLoad2(LLVMTypeRef.Int32, length, "finalLength");
    _builder.BuildRet(finalLength);
}
```

However, when I tried to do something like `var length = _builder.BuildCall2(_module.GetNamedFunction("strlen").TypeOf, _module.GetNamedFunction("strlen"), [/*valueRef here*/]);`
I always got an AccessViolationException.
At first, I thought it was an issue with my code, but after 2-3 hours of debugging and conferring with peers, no answers could be found. Please help

**Comment by davidelettieri** [comment]
Hi, I think the problem might be similar to this https://github.com/dotnet/LLVMSharp/issues/221#issuecomment-2177832778

If you look at the implementation of the `TypeOf` property on `LLVMValueRef` you can see 

```csharp
public LLVMTypeRef TypeOf => (Handle != IntPtr.Zero) ? LLVM.TypeOf(this) : default;
```

However the `LLVM.TypeOf` method is not working anymore on types of kind `LLVMPointerTypeKind`. I think you have two options:
1. You know the type of the function because you are defining it so you can rebuild the type as you did when defining `strlenType`.
2. Retrieve the type using `LLVM.GlobalGetValueType` on the function.

In case of 2 you will have 

```csharp
var func = _module.GetNamedFunction("strlen");
var funcType = LLVM.GlobalGetValueType(func);
var v = _builder.BuildCall2(funcType2, func, [/*valueRef here*/]);
```

Let me know if this helps.

**Comment by DuncanMcPherson** [comment]
> Let me know if this helps.

Thank you so much! I had been working at that issue for 3 days! and the second approach worked perfectly!
